services:
  codebook_server:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: codebook
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app/src
      - ./docs:/app/docs
      - ./blog:/app/blog
      - ./static:/app/static
      - /app/node_modules/
      - ./docusaurus.config.js:/app/docusaurus.config.js
      - ./sidebars.js:/app/sidebars.js
