// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  /** LANGUAGES */
  Pytyhon: [{ type: "autogenerated", dirName: "languages/python" }],
  JavaScript: [{ type: "autogenerated", dirName: "languages/javascript" }],
  Java: [{ type: "autogenerated", dirName: "languages/java" }],
  Cs: [{ type: "autogenerated", dirName: "languages/cs" }],
  SQL: [{ type: "autogenerated", dirName: "languages/sql" }],
  Docker: [{ type: "autogenerated", dirName: "languages/docker" }],

  /** RECEPIES */
  HTML_CSS: [{ type: "autogenerated", dirName: "recepies/html_css" }],
  Express: [{ type: "autogenerated", dirName: "recepies/express" }],
  React: [{ type: "autogenerated", dirName: "recepies/react" }],
  FastApi: [{ type: "autogenerated", dirName: "recepies/fastapi" }],
  SpringBoot: [{ type: "autogenerated", dirName: "recepies/springboot" }],
  aspnet: [{ type: "autogenerated", dirName: "recepies/asp.net" }],
  docker: [{ type: "autogenerated", dirName: "recepies/devops" }],
};

export default sidebars;
